# Generated by Django 2.2 on 2019-04-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrautomationapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextension',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
